// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../app/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/automations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automations">> = Specific
  const handler = {} as typeof import("../../app/automations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/briefing/[itemId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/briefing/[itemId]">> = Specific
  const handler = {} as typeof import("../../app/briefing/[itemId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/briefing/digests/[digestId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/briefing/digests/[digestId]">> = Specific
  const handler = {} as typeof import("../../app/briefing/digests/[digestId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/briefing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/briefing">> = Specific
  const handler = {} as typeof import("../../app/briefing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/decisions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/decisions">> = Specific
  const handler = {} as typeof import("../../app/decisions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/experimental/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/experimental/chat">> = Specific
  const handler = {} as typeof import("../../app/experimental/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/matters/[matterId]/decision-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matters/[matterId]/decision-map">> = Specific
  const handler = {} as typeof import("../../app/matters/[matterId]/decision-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/matters/[matterId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matters/[matterId]">> = Specific
  const handler = {} as typeof import("../../app/matters/[matterId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/matters/[matterId]/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matters/[matterId]/research">> = Specific
  const handler = {} as typeof import("../../app/matters/[matterId]/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/matters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matters">> = Specific
  const handler = {} as typeof import("../../app/matters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/matters/storage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matters/storage">> = Specific
  const handler = {} as typeof import("../../app/matters/storage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/skills">> = Specific
  const handler = {} as typeof import("../../app/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/watches/[watchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/watches/[watchId]">> = Specific
  const handler = {} as typeof import("../../app/watches/[watchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/watches/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/watches/new">> = Specific
  const handler = {} as typeof import("../../app/watches/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/watches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/watches">> = Specific
  const handler = {} as typeof import("../../app/watches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../app/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
