import type { DecisionMapNode, DecisionPathPrefill, IssueAnalysis, IssueAnalysisStatus, IssueOption } from "@/lib/decisionMapTypes";
import type { DocumentReferenceTarget } from "@/lib/workspaceTypes";
import { nodeStateLabel } from "@/lib/decisionMapLayout";
import styles from "./MatterMap.module.css";

function optionFromNode(node: DecisionMapNode): IssueOption | null {
  const candidate = node.data as Partial<IssueOption> | undefined;
  return candidate?.option_id && candidate.option_revision && candidate.title ? candidate as IssueOption : null;
}

export function recordPrefill(node: DecisionMapNode, analysis: IssueAnalysis, status: IssueAnalysisStatus): DecisionPathPrefill | null {
  const option = optionFromNode(node);
  if (!option || node.hypothetical || node.group === "hypothetical" || node.analysis_id !== analysis.analysis_id || node.analysis_revision !== analysis.analysis_revision || node.output_revision !== analysis.output_revision) return null;
  return { map_basis: { issue_id: analysis.issue_id, analysis_id: analysis.analysis_id, analysis_revision: analysis.analysis_revision, analysis_path: analysis.source_path, output_revision: analysis.output_revision, selected_option_id: option.option_id, selected_option_revision: option.option_revision, canonical_option: option, input_basis: analysis.input_basis }, option, analysis, state: status.state };
}

export default function DecisionMapInspector({ focusedIssueId, node, status, onAnalyzePaths, onRecordPath, onSelectNode, onDiscuss, onTryDifferentAssumption, onBackToIssue, onOpenDocument }: { focusedIssueId: string | null; node: DecisionMapNode | null; status: IssueAnalysisStatus | null; onAnalyzePaths?: (issueId: string) => void; onRecordPath?: (prefill: DecisionPathPrefill) => void; onSelectNode: (id: string | null) => void; onDiscuss: () => void; onTryDifferentAssumption: () => void; onBackToIssue: () => void; onOpenDocument: (target: DocumentReferenceTarget) => void }) {
  const analysis = status?.analysis ?? null;
  const prefill = node && analysis ? recordPrefill(node, analysis, status!) : null;
  const needsAnalysis = !analysis || ["not_mapped", "partial", "missing", "needs_review"].includes(status?.state ?? "not_mapped");
  const detail = node?.detail ?? (node?.data?.summary as string | undefined) ?? null;
  const legalTest = node?.record_type === "legal_test" ? node.data as Record<string, unknown> | undefined : undefined;
  const selectedOption = node ? optionFromNode(node) : null;
  const conditionQuestion = new Map((analysis?.conditions ?? []).map((condition) => [condition.condition_id, condition.question]));
  const businessEffect = analysis?.business_effect?.trim() || null;
  const repeatsBusinessEffect = Boolean(businessEffect && selectedOption?.consequence && selectedOption.consequence.trim().toLowerCase() === businessEffect.toLowerCase());
  const claimSupport = Array.isArray(node?.data?.claim_support) ? node.data.claim_support as Array<Record<string, unknown>> : [];
  const sources = claimSupport.flatMap((claim) => Array.isArray(claim.evidence) ? claim.evidence.filter((value): value is Record<string, unknown> => Boolean(value && typeof value === "object")).map((evidence) => ({ ...evidence, claim_id: evidence.claim_id ?? claim.claim_id })) : [claim]);
  const sourceTarget = (source: Record<string, unknown>): DocumentReferenceTarget | null => typeof source.path === "string" && typeof (source.document_id ?? source.source_id) === "string" ? { document_id: String(source.document_id ?? source.source_id), path: source.path, revision: typeof source.source_version === "string" ? source.source_version : typeof source.source_revision === "string" ? source.source_revision : null, locator: typeof source.locator === "string" ? source.locator : undefined, available_excerpt: typeof source.available_excerpt === "string" ? source.available_excerpt : null, exact_passage_available: Boolean(source.available_excerpt), origin: { surface: "decision_map", record_id: node?.node_id ?? null } } : null;
  return <aside aria-label="Decision path details" className={`${styles.card} ${styles.inspector}`}>
    <div className={styles.inspectorHead}><div><span className={styles.meta}>{node ? "Selected record" : "This issue"}</span><h2 className={styles.selectedTitle}>{node?.label ?? analysis?.display_title ?? "Select a path"}</h2>{node ? <span className={`state-label ${styles.inspectorState}`}>{nodeStateLabel(node)}</span> : null}</div><div className={styles.inspectorActions}><button className="btn quiet" onClick={() => onSelectNode(null)} type="button">Clear selection</button><button className="btn quiet" disabled={!focusedIssueId} onClick={onBackToIssue} type="button">Back to issue</button></div></div>
    {node?.record_type === "option" && selectedOption ? <div className={styles.inspectorColumns}><section><h3>Consequence</h3><p>{selectedOption.consequence || "No consequence saved."}</p>{selectedOption.trade_off ? <><h3>Trade-off</h3><p>{selectedOption.trade_off}</p></> : null}</section><section><h3>Requirements</h3><p>{selectedOption.condition_summary}</p>{selectedOption.requirements.length ? <p>{selectedOption.combination === "any" ? "Any listed condition can support this route." : "All listed conditions apply to this route."} {selectedOption.requirements.map((requirement) => `${conditionQuestion.get(requirement.condition_id) ?? requirement.condition_id} — must be ${requirement.state.replace(/_/g, " ")}`).join("; ")}</p> : <p>Business alternative. No condition is treated as satisfied.</p>}<h3>Remaining work</h3>{selectedOption.remaining_work.length ? <ul>{selectedOption.remaining_work.map((work) => <li key={work}>{work}</li>)}</ul> : <p>None saved.</p>}</section><section><h3>Recommendation</h3><p>{selectedOption.recommendation === "recommended" ? "Recommended by the agent" : "Alternative identified by the agent"}</p>{selectedOption.recommendation_reason ? <p>{selectedOption.recommendation_reason}</p> : null}</section></div> : legalTest ? <div className={styles.inspectorColumns}><section><h3>Summary</h3><p>{String(legalTest.summary ?? detail ?? "No summary saved.")}</p><h3>Applicability</h3><p>{String(legalTest.applicability ?? "No applicability statement saved.")}</p></section><section><h3>Actor</h3><p>{String(legalTest.actor ?? "Not specified")}</p><h3>Jurisdiction</h3><p>{String(legalTest.jurisdiction ?? "Not specified")}</p></section><section><h3>Effective date</h3><p>{String(legalTest.effective_at ?? "Not specified")}</p><h3>Exceptions</h3><p>{String(legalTest.exceptions ?? "None saved.")}</p></section></div> : detail ? <p className={styles.inspectorDetail}>{detail}</p> : <p className={styles.muted}>Select a test, condition, fact, or path to read its saved detail.</p>}
    {businessEffect && !repeatsBusinessEffect ? <section className={styles.inspectorBusinessEffect}><h3>Business effect</h3><p>{businessEffect}</p></section> : null}
    {node?.record_type === "condition" && node.state.toLowerCase() === "unknown" ? <p className={styles.unknownNote}>Unknown. This condition does not choose a path.</p> : null}
    {sources.length ? <section className={styles.inspectorSources}><h3>Source support</h3>{sources.map((source, index) => { const target = sourceTarget(source); const label = String(source.source_label ?? source.source_id ?? source.claim_id ?? "Saved source"); return <div key={`${label}-${index}`}><span>{label}{typeof source.locator === "string" ? ` · ${source.locator}` : ""}</span>{target ? <button className="btn quiet" onClick={() => onOpenDocument(target)} type="button">Open source</button> : <span className={styles.muted}>Saved source has no open document target.</span>}</div>; })}</section> : null}
    {needsAnalysis && focusedIssueId && onAnalyzePaths ? <button className="btn primary" onClick={() => onAnalyzePaths(focusedIssueId)} type="button">{status?.state === "needs_review" ? "Update paths" : "Analyze paths"}</button> : null}
    <div className={styles.inspectorActions}><button className="btn quiet" disabled={!node} onClick={onDiscuss} type="button">Discuss this path</button><button className="btn quiet" disabled={!node} onClick={onTryDifferentAssumption} type="button">Try a different assumption</button>{prefill && onRecordPath ? <button className="btn primary" onClick={() => onRecordPath(prefill)} type="button">Record this path</button> : null}</div>
  </aside>;
}
