// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/agents" | "/automations" | "/briefing" | "/briefing/[itemId]" | "/briefing/digests/[digestId]" | "/decisions" | "/experimental/chat" | "/matters" | "/matters/[matterId]" | "/matters/[matterId]/decision-map" | "/matters/[matterId]/research" | "/matters/storage" | "/settings" | "/skills" | "/watches" | "/watches/[watchId]" | "/watches/new" | "/workspace"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/agents": {}
  "/automations": {}
  "/briefing": {}
  "/briefing/[itemId]": { "itemId": string; }
  "/briefing/digests/[digestId]": { "digestId": string; }
  "/decisions": {}
  "/experimental/chat": {}
  "/matters": {}
  "/matters/[matterId]": { "matterId": string; }
  "/matters/[matterId]/decision-map": { "matterId": string; }
  "/matters/[matterId]/research": { "matterId": string; }
  "/matters/storage": {}
  "/settings": {}
  "/skills": {}
  "/watches": {}
  "/watches/[watchId]": { "watchId": string; }
  "/watches/new": {}
  "/workspace": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
