from pathlib import Path
p=Path('.tmp/themis-v9/build.mjs')
s=p.read_text()
s=s.replace('A migration question reveals a data-use choice','A migration question hides a second decision')
s=s.replace('“Can customers keep their bank connections during the migration?”','“Can we keep bank connections live during the migration?”')
s=s.replace('Separate the new uses from the migration.\\nThen weigh a fixed reauthorization deadline\\nagainst waiting for each bank’s next event.','Separate consent for new uses.\\nThen choose when customers\\nmust authorize the migration.')
s=s.replace('The materials and the open choice, together','The lawyer has a basis for the advice')
s=s.replace("label(s,'Ready to advise',964,258,245);","label(s,'Relay demo',964,258,245);")
s=s.replace("tx(s,'The matter brings\\nthe business facts\\nand open choice\\ninto view.',964,307,248,146,25);\ntx(s,'An editable decision\\nnote sets out a\\nproposed path and\\nits conditions.',964,493,248,130,25,C.blue,'Georgia',true);", "tx(s,'A draft note sets out\\na proposed path\\nand its conditions.',964,307,248,118,25);\ntx(s,'The lawyer can test\\nthe recommendation\\nbefore giving it.',964,482,248,129,25,C.blue,'Georgia',true);")
s=s.replace('The working habits of legal AI are forming now','Legal teams are forming their AI habits')
s=s.replace('An unfamiliar issue lands before a launch.\\nThe lawyer has AI tools but little support.\\nThey need to understand enough to advise.','An unfamiliar issue before a launch.\\nAI tools, but little associate support.\\nA decision that cannot wait.')
s=s.replace('Track readiness to advise alongside\\nnet time saved.','Test readiness to advise\\nand net time saved.')
s=s.replace('Does Themis surface material issues\\nwith less lawyer steering?','Useful issues surfaced\\nwith less lawyer steering')
p.write_text(s)
final=Path('output/deck/vc/Themis-VC-Pitch-September-2026-v9.pptx')
final.rename('.tmp/themis-v9/first-pass.pptx')
f=Path('.tmp/themis-v9/finalize.mjs');f.write_text(f.read_text().replace('validation-v9-final.json','validation-v9-reviewed.json'))
